@host = localhost:8080

###
# @name createTask
POST http://{{host}}/task HTTP/1.1
content-type: application/json

{
    "title": "Develop API",
    "content": "Use actix framework for developing the API"
}
###

# @name updateTask
PATCH http://{{host}}/task?id={{createTask.response.body.*}} HTTP/1.1
content-type: application/json

[
  { "op": "replace", "path": "/content", "value": "New content for API task" }
]
###

# @name getTask
GET http://{{host}}/task?id={{createTask.response.body.*}} HTTP/1.1
###
# @name  deleteTask
DELETE http://{{host}}/task?id={{createTask.response.body.*}} HTTP/1.1
###